# Generated by Django 5.2.8 on 2025-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_stor', '0007_carorder_carreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='car_stor.accessory'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='car_stor.car'),
        ),
    ]
