from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('car/<int:car_id>/', views.car_detail, name='car_detail'),
    path('car/add/', views.car_create, name='car_create'),
    path('car/<int:car_id>/edit/', views.car_update, name='car_update'),
    path('car/<int:car_id>/delete/', views.car_delete, name='car_delete'),
    path('inventory/', views.car_inventory, name='car_inventory'),
    path('inventory/category/<int:category_id>/', views.car_inventory, name='car_inventory_category'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    
    path('accessories/', views.grid, name='grid'),
    path('accessories/category/<int:category_id>/', views.grid, name='grid_category'),
    path('accessory/<int:accessory_id>/', views.accessory_detail, name='accessory_detail'),
    path('accessory/add/', views.accessory_create, name='accessory_create'),
    path('accessory/<int:pk>/edit/', views.accessory_update, name='accessory_update'),
    path('accessory/<int:pk>/delete/', views.accessory_delete, name='accessory_delete'),
    path('list/', views.list_cars, name='list'),
    path('list1/', views.list_accessories, name='list1'),
    path('list1/category/<int:category_id>/', views.list_accessories, name='list1_category'),
    path('blog/', views.blog, name='blog'),
    path('blog/<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('compare/', views.compare, name='compare'),
    path('about-us/', views.about_us, name='about_us'),
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('cart/add/<int:accessory_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/process/', views.process_checkout, name='process_checkout'),
    path('checkout_method/', views.checkout_method, name='checkout_method'),
    path('checkout_billing_info/', views.checkout_billing_info, name='checkout_billing_info'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/toggle/<int:car_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('wishlist/toggle/accessory/<int:accessory_id>/', views.toggle_wishlist_accessory, name='toggle_wishlist_accessory'),
    path('wishlist/add_all/', views.wishlist_add_all_to_cart, name='wishlist_add_all_to_cart'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('multiple_addresses/', views.multiple_addresses, name='multiple_addresses'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('404error/', views.error_404, name='404error'),
    path('quickview/', views.quickview, name='quickview'),
    path('car/<int:car_id>/checkout/', views.car_checkout, name='car_checkout'),
    path('car/order/success/', views.order_success, name='order_success'),
    path('car/order/<int:order_id>/approve/', views.approve_car_order, name='approve_car_order'),
    path('car/order/<int:order_id>/decline/', views.decline_car_order, name='decline_car_order'),
    path('accessory/order/<int:order_id>/approve/', views.approve_accessory_order, name='approve_accessory_order'),
    path('accessory/order/<int:order_id>/decline/', views.decline_accessory_order, name='decline_accessory_order'),
    path('newsletter/', views.newsletter, name='newsletter'),
    
    # Notifications URLs
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:notification_id>/mark-read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('site-admin/category/add/', views.category_create, name='category_create'),
    path('site-admin/category/<int:pk>/edit/', views.category_update, name='category_update'),
    path('site-admin/category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    
    path('site-admin/blog/add/', views.blog_create, name='blog_create'),
    path('site-admin/blog/<int:post_id>/edit/', views.blog_update, name='blog_update'),
    path('site-admin/blog/<int:post_id>/delete/', views.blog_delete, name='blog_delete'),
    
    path('site-admin/user/add/', views.admin_user_create, name='admin_user_create'),
    path('site-admin/user/<int:user_id>/edit/', views.admin_user_edit, name='admin_user_edit'),
    path('site-admin/user/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('site-admin/user/<int:user_id>/toggle-staff/', views.toggle_staff_status, name='toggle_staff_status'),
    
    path('notifications/<int:notification_id>/delete/', views.delete_notification, name='delete_notification'),
    path('test-csrf-exempt/', views.myview, name='myview'),
    path('test-xframe-exempt/', views.view1, name='view1'),
]
